-- Part 1: Customer & Order Fundamentals
-- total orders
SELECT COUNT(order_id) AS total_orders 
FROM "FactOrders";

-- unique customers
SELECT COUNT(DISTINCT customer_id) AS unique_customers 
FROM "FactOrders";

-- cities generate the highest number of orders
SELECT 
    c.city, 
    COUNT(o.order_id) AS total_orders
FROM "DimCustomers" c
JOIN "FactOrders" o ON c."Customer_id" = o.customer_id
GROUP BY c.city
ORDER BY total_orders DESC;

-- percentage of customers have placed more than one order
WITH CustomerOrders AS (
    SELECT customer_id, COUNT(order_id) AS order_count 
    FROM "FactOrders" 
    GROUP BY customer_id
)
SELECT (SELECT COUNT(*) FROM CustomerOrders WHERE order_count > 1) * 100.0 / 
       (SELECT COUNT(*) FROM CustomerOrders) AS Percentage_Repeat_Customers;

--monthly trend of total orders over time
SELECT 
    TO_CHAR(order_date::DATE, 'YYYY-MM') AS Month, 
    COUNT(order_id) AS Total_Orders 
FROM "FactOrders" 
GROUP BY Month 
ORDER BY Month;

--Part 2: Revenue & Product Performance
--total revenue generated by UrbanCart
SELECT SUM(oi.quantity::INTEGER * p.unit_price::NUMERIC) AS Total_Revenue 
FROM "FactOrderItems" oi 
JOIN "DimProducts" p ON oi.product_id = p.product_id;

--product categories contribute the most to total revenue
SELECT 
    p.category, 
    SUM(oi.quantity::INTEGER * p.unit_price::NUMERIC) AS Category_Revenue 
FROM "FactOrderItems" oi 
JOIN "DimProducts" p ON oi.product_id = p.product_id 
GROUP BY p.category 
ORDER BY Category_Revenue DESC;

--individual products generate the highest revenue
SELECT p.product_name, SUM(oi.quantity::INTEGER * p.unit_price::NUMERIC) AS product_revenue 
FROM "FactOrderItems" oi 
JOIN "DimProducts" p ON oi.product_id = p.product_id 
GROUP BY p.product_name 
ORDER BY product_revenue DESC 
LIMIT 10;

--Average Order Value (AOV) and Average Basket Size
SELECT 
    (SUM(oi.quantity::INTEGER * p.unit_price::NUMERIC) / COUNT(DISTINCT oi.order_id)) AS AOV,
    AVG(order_qty.total_items) AS average_basket_size
FROM "FactOrderItems" oi
JOIN "DimProducts" p ON oi.product_id = p.product_id
CROSS JOIN (
    SELECT order_id, SUM(quantity::INTEGER) AS total_items 
    FROM "FactOrderItems" 
    GROUP BY order_id
) order_qty;

--Products at risk of stock-out (low inventory vs. high sales)
SELECT p.product_name, p.stock::INTEGER, SUM(oi.quantity::INTEGER) AS total_sold 
FROM "DimProducts" p 
JOIN "FactOrderItems" oi ON p.product_id = oi.product_id 
GROUP BY p.product_name, p.stock 
ORDER BY p.stock::INTEGER ASC, total_sold DESC 
LIMIT 10;

--3. Customer Behavior & Segmentation
--Customers contributing the highest revenue

SELECT 
    c.full_name, 
    SUM(oi.quantity::INTEGER * p.unit_price::NUMERIC) AS Customer_Revenue 
FROM "FactOrderItems" oi 
JOIN "FactOrders" o ON oi.order_id = o.order_id 
JOIN "DimProducts" p ON oi.product_id = p.product_id 
JOIN "DimCustomers" c ON o.customer_id = c."Customer_id" 
GROUP BY c.full_name 
ORDER BY Customer_Revenue DESC 
LIMIT 10;;

--Average number of unique products per order
SELECT AVG(unique_items) AS avg_items_per_order 
FROM (
    SELECT order_id, COUNT(product_id) AS unique_items 
    FROM "FactOrderItems" 
    GROUP BY order_id
) sub;

--Purchasing patterns by gender and category
SELECT c."Gender", p.category, SUM(oi.quantity::INTEGER) AS total_quantity 
FROM "FactOrderItems" oi 
JOIN "FactOrders" o ON oi.order_id = o.order_id 
JOIN "DimProducts" p ON oi.product_id = p.product_id 
JOIN "DimCustomers" c ON o.customer_id = c."Customer_id" 
GROUP BY c."Gender", p.category 
ORDER BY c."Gender", total_quantity DESC;

--Cities with the highest Average Order Value
SELECT c.city, SUM(oi.quantity::INTEGER * p.unit_price::NUMERIC) / COUNT(DISTINCT o.order_id) AS city_aov 
FROM "FactOrderItems" oi 
JOIN "FactOrders" o ON oi.order_id = o.order_id 
JOIN "DimProducts" p ON oi.product_id = p.product_id 
JOIN "DimCustomers" c ON o.customer_id = c."Customer_id" 
GROUP BY c.city 
ORDER BY city_aov DESC;

--customer purchasing behavior change over time since account creation
SELECT (o.order_date::DATE - c.created_at::DATE) AS days_since_creation, COUNT(o.order_id) AS order_count 
FROM "FactOrders" o 
JOIN "DimCustomers" c ON o.customer_id = c."Customer_id"
GROUP BY days_since_creation 
ORDER BY days_since_creation;

--Part 4: Payment & Order Flow Insights
--Which payment methods are used most frequently?
SELECT method, COUNT(*) AS usage_count 
FROM "FactPayments" 
GROUP BY method 
ORDER BY usage_count DESC;

--Relationship between payment method and order status
SELECT p.method, o.status, COUNT(*) AS count 
FROM "FactPayments" p 
JOIN "FactOrders" o ON p.order_id = o.order_id 
GROUP BY p.method, o.status 
ORDER BY p.method, count DESC;

--City preferences for specific payment methods
SELECT c.city, p.method, COUNT(*) AS count 
FROM "FactPayments" p 
JOIN "FactOrders" o ON p.order_id = o.order_id 
JOIN "DimCustomers" c ON o.customer_id = c."Customer_id"
GROUP BY c.city, p.method 
ORDER BY c.city, count DESC;

--Payment methods associated with higher-value orders
SELECT py.method, AVG(v.order_value) AS avg_order_value 
FROM (
    SELECT order_id, SUM(quantity::INTEGER * unit_price::NUMERIC) AS order_value 
    FROM "FactOrderItems" JOIN "DimProducts" USING (product_id) 
    GROUP BY order_id
) v 
JOIN "FactPayments" py ON v.order_id = py.order_id 
GROUP BY py.method 
ORDER BY avg_order_value DESC;

--Average items per order by payment method
SELECT py.method, AVG(v.total_qty) AS avg_items_per_order 
FROM (
    SELECT order_id, SUM(quantity::INTEGER) AS total_qty 
    FROM "FactOrderItems" 
    GROUP BY order_id
) v 
JOIN "FactPayments" py ON v.order_id = py.order_id 
GROUP BY py.method 
ORDER BY avg_items_per_order DESC;

--products are most frequently ordered together
SELECT 
    p1.product_name AS Product_1, 
    p2.product_name AS Product_2, 
    COUNT(*) AS Frequency 
FROM "FactOrderItems" oi1 
JOIN "FactOrderItems" oi2 ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id 
JOIN "DimProducts" p1 ON oi1.product_id = p1.product_id 
JOIN "DimProducts" p2 ON oi2.product_id = p2.product_id 
GROUP BY Product_1, Product_2 
ORDER BY Frequency DESC 
LIMIT 15;

--product pairs appear most often across all orders
SELECT 
    p1.product_name AS Item_A, 
    p2.product_name AS Item_B, 
    COUNT(*) AS Pair_Occurrence 
FROM "FactOrderItems" oi1 
JOIN "FactOrderItems" oi2 ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id 
JOIN "DimProducts" p1 ON oi1.product_id = p1.product_id 
JOIN "DimProducts" p2 ON oi2.product_id = p2.product_id 
GROUP BY Item_A, Item_B 
ORDER BY Pair_Occurrence DESC 
LIMIT 15;

--Product pairs consistently driving higher order values
SELECT p1.product_name AS product_a, p2.product_name AS product_b, AVG(v.order_value) AS avg_order_val 
FROM "FactOrderItems" oi1 
JOIN "FactOrderItems" oi2 ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id 
JOIN "DimProducts" p1 ON oi1.product_id = p1.product_id 
JOIN "DimProducts" p2 ON oi2.product_id = p2.product_id 
JOIN (
    SELECT order_id, SUM(quantity::INTEGER * unit_price::NUMERIC) AS order_value 
    FROM "FactOrderItems" JOIN "DimProducts" USING (product_id) 
    GROUP BY order_id
) v ON oi1.order_id = v.order_id 
GROUP BY product_a, product_b 
ORDER BY avg_order_val DESC 
LIMIT 20;

--Recommended product bundles for revenue increase
SELECT p1.product_name AS item_1, p2.product_name AS item_2, COUNT(*) AS frequency, AVG(v.val) AS avg_revenue 
FROM "FactOrderItems" oi1 
JOIN "FactOrderItems" oi2 ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id 
JOIN "DimProducts" p1 ON oi1.product_id = p1.product_id 
JOIN "DimProducts" p2 ON oi2.product_id = p2.product_id 
JOIN (SELECT order_id, SUM(quantity::INTEGER * unit_price::NUMERIC) AS val FROM "FactOrderItems" JOIN "DimProducts" USING (product_id) GROUP BY 1) v ON oi1.order_id = v.order_id
GROUP BY 1, 2 
HAVING COUNT(*) > 5 
ORDER BY avg_revenue DESC LIMIT 15;

--Products to promote together (Cross-category opportunities)
SELECT p1.category AS cat_1, p1.product_name AS prod_1, p2.category AS cat_2, p2.product_name AS prod_2, COUNT(*) AS frequency 
FROM "FactOrderItems" oi1 
JOIN "FactOrderItems" oi2 ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id 
JOIN "DimProducts" p1 ON oi1.product_id = p1.product_id 
JOIN "DimProducts" p2 ON oi2.product_id = p2.product_id 
WHERE p1.category <> p2.category 
GROUP BY 1, 2, 3, 4 
ORDER BY frequency DESC 
LIMIT 15;